version: "3.8"
services:
  eureka:
    image: gigagibi/rtuitlab-2022-eureka
    container_name: eureka
    restart: always
    ports:
      - "8761:8761"

  orders_mongodb:
    image: mongo
    container_name: orders_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - orders_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
  orders:
    image: gigagibi/rtuitlab-2022-orders
    container_name: orders
    restart: always
    ports:
      - "3501:3501"
    depends_on:
      - orders_mongodb
      - eureka
      - rabbitmq
      - products
    environment:
      - SPRING_MONGO_URI=mongodb://root:root@orders_mongodb:27017/rtu_orders?authSource=admin
      - SPRING_EUREKA_HOST=http://eureka:8761/eureka
      - RABBITMQ_HOST=rabbitmq

  supplies_mongodb:
    image: mongo
    container_name: supplies_mongo
    restart: always
    ports:
      - "27018:27017"
    volumes:
      - supplies_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
  supplies:
    image: gigagibi/rtuitlab-2022-supplies
    container_name: supplies
    restart: always
    ports:
      - "3503:3503"
    depends_on:
      - supplies_mongodb
      - eureka
    environment:
      - SPRING_MONGO_URI=mongodb://root:root@supplies_mongodb:27017/rtu_supplies?authSource=admin
      - SPRING_EUREKA_HOST=http://eureka:8761/eureka

  products_postgresdb:
    image: postgres
    container_name: products_postgres
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - products_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=rtu_products
  products:
    image: gigagibi/rtuitlab-2022-products
    container_name: products
    restart: always
    ports:
      - "3502:3502"
    depends_on:
      - products_postgresdb
      - eureka
      - rabbitmq
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://products_postgresdb:5432/rtu_products
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_EUREKA_HOST=http://eureka:8761/eureka
      - RABBITMQ_HOST=rabbitmq

  gateway:
    image: gigagibi/rtuitlab-2022-gateway
    container_name: gateway
    restart: always
    environment:
      - SPRING_EUREKA_HOST=http://eureka:8761/eureka
    ports:
      - "3500:3500"
    depends_on:
      - eureka
      - orders
      - supplies
      - products
      - deliveries

  deliveries_postgres:
      image: postgres
      container_name: deliveries_postgres
      restart: always
      ports:
        - "5434:5432"
      volumes:
        - ./deliveries/src/main/docker/init.sql:/docker-entrypoint-initdb.d/init.sql
        - deliveries_data:/var/lib/postgresql/data
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=root
        - POSTGRES_DB=rtu_deliveries
  deliveries:
    image: gigagibi/rtuitlab-2022-deliveries
    container_name: deliveries
    ports:
      - "3505:3505"
    depends_on:
      - deliveries_postgres
      - eureka
      - rabbitmq
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://deliveries_postgres:5432/rtu_deliveries
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_EUREKA_HOST=http://eureka:8761/eureka
      - JWT_SECRET=secret
      - RABBITMQ_HOST=rabbitmq

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
volumes:
  orders_data:
  supplies_data:
  products_data:
  deliveries_data: