version: "3.8"
services:
  orders_mongodb:
    image: mongo
    container_name: orders_mongo
    ports:
      - "27017:27017"
    volumes:
      - orders_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root

  supplies_mongodb:
    image: mongo
    container_name: supplies_mongo
    ports:
      - "27018:27017"
    volumes:
      - supplies_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root

  orders_mongo_express:
    image: mongo-express
    container_name: orders_mongo_express
    restart: always
    depends_on:
      - orders_mongodb
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
      - ME_CONFIG_MONGODB_SERVER=orders_mongodb
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
  supplies_mongo_express:
    image: mongo-express
    container_name: supplies_mongo_express
    restart: always
    depends_on:
      - supplies_mongodb
    ports:
      - "8082:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
      - ME_CONFIG_MONGODB_SERVER=supplies_mongodb
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_PORT=27017
  products_postgresdb:
    image: postgres
    container_name: products_postgres
    ports:
      - "5432:5432"
    volumes:
      - products_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=rtu_products
volumes:
  orders_data:
  supplies_data:
  products_data:
