spring:
  application:
    name: orders
  data:
    mongodb:
      auto-index-creation: true
      authentication-database: admin
      uri: ${SPRING_MONGO_URI}
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: ${SPRING_EUREKA_HOST}
server:
  port: 3501
rabbitmq:
  host: ${RABBITMQ_HOST}