spring:
  application:
    name: products
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
  datasource:
    url: jdbc:postgresql://localhost:5432/rtu_products
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root