spring:
  application:
    name: products
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true
  datasource:
    url: jdbc:postgresql://localhost:5432/rtu_products
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 3502