spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: 'true'
          lower-case-service-id: 'true'
      routes:
      - id: orders
        uri: http://orders
        predicates:
          - Path=/orders
      - id: supplies
        uri: http://supplies
        predicates:
          - Path=/supplies
      - id: menu
        uri: http://menu
        predicates:
          - Path=/menu
server:
  port: 3500
eureka:
  client:
    service-url:
      defaultZone: ${SPRING_EUREKA_HOST}
